# Generated by Django 4.2.1 on 2023-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimauxZone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaux',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animaux'},
        ),
        migrations.AlterModelOptions(
            name='zonecoeur',
            options={'verbose_name': 'Zone Coeur', 'verbose_name_plural': 'Zone Coeurs'},
        ),
        migrations.AlterField(
            model_name='animaux',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
